### PR TITLE
Added removal of extra lines, config value and tests

### LINKED ISSUE #6: Remove Extraneous Blank Lines
If my file has say 3 blank lines at the end, would it be possible to remove the extra ones, so there's exactly one blank line at the end of the file? I believe this is the behaviour of atom.

### PR DESCRIPTION
**Pull request by liqwid**
This one fixes #6

### CODE REVIEW

**Comment by riccardoNovaglia** [comment]
That's awesome! Thanks for submitting this. I'll get Vs code running locally and push out the new version today!

**Comment by riccardoNovaglia** [comment]
Sorry, just got around to checking this out. Awesome work, and thanks for the PR! I'll need to find out my credentials to publish the new version, it'll probably be this afternoon after work. I'll update you when it's live!

**Comment by riccardoNovaglia** [comment]
Just published the new version! Thanks again! 

Have a great day!

**Comment by liqwid** [comment]
Thank you for publishing, happy that now dealing with extra line mess will become easier in VsCode

**Pull request merged**
